spring:
  datasource:
    url: jdbc:sqlite:test.db
    driver: org.sqlite.JDBC
    username: sa
    passsword: sa
  batch:
    job:
      enabled: true
covid19:
  county:
    url: https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties.csv